name: CICD for Nodejs Application with Docker
run-name: ${{ github.actor }} is running CICD for Nodejs Application with Docker

on:
  push:
    branches: 
      - dev
      - feature-app
      - feature/*      
  workflow_dispatch:  

permissions:
  id-token: write

jobs:
  snyk-terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
          args: --severity-threshold=high
            --sarif-file-output=terraform.snyk.scan
          sarif: false
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: application/${{ matrix.repository }}


  build-and-push-image-to-ecr:
    runs-on: ubuntu-latest
    # Make sure to run after the "job-get-aws-info-workflow" job.
    needs: job-get-aws-info-workflow
    name: Build and Push Docker Image to ECR
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Syntax for accessing outputs from a reusable workflow is "needs.<reusable>.outputs.<output>".
          role-to-assume: ${{ needs.job-get-aws-info-workflow.outputs.role_to_assume }}
          aws-region: ${{ needs.job-get-aws-info-workflow.outputs.aws_region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create ECR repository using Terraform
        run: |
          cd ecr
          terraform init
          terraform apply -auto-approve
      - name: Build and push image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ds2-test-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-ecs:
    runs-on: ubuntu-latest
    needs: [job-get-aws-info-workflow, build-and-push-image-to-ecr] # Make sure to run after the "job-get-aws-info-workflow" job.
    name: Deploy to ECS
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Syntax for accessing outputs from a reusable workflow is "needs.<reusable>.outputs.<output>".
          role-to-assume: ${{ needs.job-get-aws-info-workflow.outputs.role_to_assume }}
          aws-region: ${{ needs.job-get-aws-info-workflow.outputs.aws_region }}
      - name: Create AWS ECS cluster, task definition and service using Terraform
        run: |
          cd ecs
          terraform init
          terraform apply -auto-approve -target=aws_ecs_cluster.ds2-test-cluster -target=aws_ecs_task_definition.ds2-test-td -target=aws_security_group.ds2-test-sg -target=aws_ecs_service.ds2-test-service
      - name: Set up Terraform outputs
        id: tf-outputsgit
        working-directory: ./ecs
        run: |
          terraform apply -auto-approve
          echo "access_url=$(terraform output -json all_access_urls | jq -r 'to_entries[0].value')" >> $GITHUB_ENV
      - name: Echo Access URL
        run: echo "The Access URL is $access_url"

  # Define the "job-get-aws-info-workflow" job, which uses a reusable workflow defined in another file. 
  job-get-aws-info-workflow:
    uses: ./.github/workflows/reusable-get-aws-info-workflow.yml