name: OIDC test only deploy on PROD
run-name: ${{ github.actor }} is doing Serverless Deployment with OIDC

on:
  pull_request:
    branches: [ "prod" ]

env:
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write

jobs:
  deploy-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run NPM clean install
        run: npm ci
      - name: Config AWS Credential with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::255945442255:role/ds-oidc-prod
          aws-region: ${{ env.AWS_REGION }}     
     - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy