name: OIDC test only deploy on PROD ENV
run-name: ${{ github.actor }} is doing PROD ENV Serverless Deployment with OIDC

on:
  pull_request:
    branches: [ "prod" ]

env:
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write

jobs:
  deploy-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::255945442255:role/ds-oidc-prod
          aws-region: ${{ env.AWS_REGION }}
      - name: Display Identity
        run: aws sts get-caller-identity
      - name: Run NPM clean install
        run: npm ci
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless Deploy
        run: serverless deploy --stage prod --verbose
